/gps/source/set 0

/gps/particle proton
# if set to ion uncomment the following line
#/gps/ion Z A Q E

/gps/direction 0 0 1

/gps/pos/type Beam
/gps/pos/shape Circle

/gps/pos/centre 0. 0. -1. mm

/gps/pos/radius 1. mm
#/gps/pos/sigma_r 0.1 mm

# put the source in the x-y plane
/gps/pos/rot1 1. 1. 0.

#/gps/ene/type Gauss
#/gps/ene/mono 150.0 MeV
#/gps/ene/sigma 1.5 MeV

/gps/ene/type Mono
/gps/ene/mono 150.0 MeV
